### ISSUE TITLE
POST, PUT, DELETE methods

### ISSUE THREAD

**Issue by yorgomoubayed** [SihemBouhenniche/NeomodelAPI#2]
Hi,

The POST, PUT and DELETE methods don't seem to work. Am I doing something wrong? Can you please give me some hints?

Thank you,

**Comment by SihemBouhenniche** [comment]
You should use neomodel ogm (object graph mapper) I recommend you to see the official documentation of neomodel for more details : 
https://neomodel.readthedocs.io/en/latest/
Or you can consult this small tutorial :
https://medium.com/swlh/create-rest-api-with-django-and-neo4j-database-using-django-nemodel-1290da717df9

**Comment by yorgomoubayed** [comment]
Hi again,

I've actually been through the tutorial, the getAllPersons and get methods of the second function work perfectly fine, but the others don't seem to work properly. Could you please provide with an example of how you would submit a POST request through Postman, or maybe even a DELETE request? 

Thank you,

**Comment by SihemBouhenniche** [comment]
Hi,
Did you setup Midlware correctly in the settings.py file
It must look like that:
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
],
If you didn't add this line:
django.middleware.csrf.CsrfViewMiddleware
@csrf_exempt decorator may not working properly.

**Comment by yorgomoubayed** [comment]
I actually cloned your repo as is so everything is in place, but when I run the POST or DELETE method I get 
JSONDecodeError: Expecting value: line 1 column 1 (char 0). Did you encounter this? Or know how to solve it?

**Comment by SihemBouhenniche** [comment]
I guess that the problem is due to json.loads()
Did you send data in encoded as json ?
This exception means that you json.loads cannot parse request.body (becasue you are not sending JSON). 
json.loads expects a JSON string,

**Comment by yorgomoubayed** [comment]
Could you please provide me with an example of how one would send JSON encoded data with the POST method in Postman? I'm a total rookie in this! Thank you for any help,

**Comment by SihemBouhenniche** [comment]
No problem at all, so you can send json data in postman like that:
![1615456451667_image](https://user-images.githubusercontent.com/32648972/110769232-3dc53780-8258-11eb-9b31-5679557c3e6e.png)
Or you can consult this tutorial:
https://medium.com/@thejasonfile/a-pithy-perusal-of-post-and-put-and-patch-52a7f6443ceb#:~:text=POST%20requests&text=In%20Postman%2C%20change%20the%20method,along%20with%20the%20POST%20request.&text=If%20this%20is%20successful%2C%20you,new%20data%20in%20your%20'db

**Comment by yorgomoubayed** [comment]
Thank you for the details! This would help me greatly!
